[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["panic_immediate_abort"]

[build]
target = "x86_64-unknown-uefi"

[target.x86_64-unknown-uefi]
rustflags = [
  "-C", "panic=abort",
]
