[build]
target = "x86_64-unknown-none"

[unstable]
build-std = ["core", "alloc"]

[target.x86_64-unknown-none]
rustflags = [
  "-C", "relocation-model=static",
  "-C", "code-model=kernel",
  "-C", "link-arg=-Tkernel.ld",
  "-C", "link-arg=-no-pie",
  "-C", "no-redzone=true",
]