[build]
target = "x86_64-unknown-none"

[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["panic_immediate_abort"]

[target.x86_64-unknown-none]
rustflags = [
  "-C", "relocation-model=static",
  "-C", "link-arg=-Tkernel.ld",
  "-C", "link-arg=-no-pie",
  "-C", "force-frame-pointers=yes"
]